# Generated by Django 3.2.6 on 2021-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('url', models.URLField(verbose_name='Ссылка на скачивание')),
            ],
        ),
    ]
