# Generated by Django 3.2.6 on 2021-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictirbution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField()),
                ('name', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('main_text', models.TextField(verbose_name='Текст рассылки')),
                ('content_url', models.URLField(null=True, verbose_name='Ссылка на контент')),
                ('button_url', models.URLField(null=True, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
