# Generated by Django 3.2.6 on 2021-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210815_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictirbution',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Было отправлено?'),
        ),
    ]
