# Generated by Django 3.2.6 on 2021-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_dictirbution_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=200, verbose_name='Тип активности')),
                ('element_unique_id', models.CharField(max_length=200, verbose_name='Айди элемент активности')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.AlterField(
            model_name='dictirbution',
            name='send_time',
            field=models.DateTimeField(verbose_name='Время отправки'),
        ),
    ]
