# Generated by Django 3.2.6 on 2021-08-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_message_unique_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dictirbution',
            new_name='Dictribution',
        ),
    ]
