# Generated by Django 3.2.6 on 2021-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_dictirbution_dictribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictribution',
            name='button_text',
            field=models.CharField(default='Нажми!', max_length=20, verbose_name='Текст кнопки'),
        ),
    ]
