# Generated by Django 3.2.6 on 2021-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_dictribution_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='stat_count_first_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
