# Generated by Django 3.2.6 on 2021-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_film_stat_count_first_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='stat_count_first_places',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
